### ISSUE TITLE
The app does not run

### ISSUE THREAD

**Issue by ghost** [Bezronczek/rc-cms#3]
I tried to run this with "npm start" as descipted, but it does not work.
Debug log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle rc-cms@0.0.1~prestart: rc-cms@0.0.1
6 silly lifecycle rc-cms@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle rc-cms@0.0.1~start: rc-cms@0.0.1
8 verbose lifecycle rc-cms@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle rc-cms@0.0.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Dev\_waw\node\rc-cms\node_modules\.bin;C:\Program Files\nodejs;C:\Program Files (x86)\iis express\PHP\v5.4;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files (x86)\WinMerge;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Users\bartlomiej.gasior\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\bartlomiej.gasior\AppData\Local\Programs\Python\Python35-32\;C:\Users\bartlomiej.gasior\AppData\Roaming\npm;C:\Program Files\Docker Toolbox;C:\Users\bartlomiej.gasior\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\bartlomiej.gasior\AppData\Local\Programs\Python\Python35-32\;C:\Users\bartlomiej.gasior\AppData\Roaming\npm;C:\Program Files\Docker Toolbox
10 verbose lifecycle rc-cms@0.0.1~start: CWD: C:\Dev\_waw\node\rc-cms
11 silly lifecycle rc-cms@0.0.1~start: Args: [ '/d /s /c', 'node server\\index.js' ]
12 silly lifecycle rc-cms@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle rc-cms@0.0.1~start: Failed to exec start script
14 verbose stack Error: rc-cms@0.0.1 start: `node server\index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid rc-cms@0.0.1
16 verbose cwd C:\Dev\_waw\node\rc-cms
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.7.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error rc-cms@0.0.1 start: `node server\index.js`
22 error Exit status 1
23 error Failed at the rc-cms@0.0.1 start script 'node server\index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the rc-cms package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server\index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs rc-cms
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls rc-cms
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Bezronczek** [comment]
Issue caused by native module sharp.
It will be replaced by full js module.

**Comment by Bezronczek** [comment]
Should work as expected now.
